FROM datadog/agent:7

ENV DD_APM_ENABLED=true
ENV NON_LOCAL_TRAFFIC=true
ENV DD_APM_NON_LOCAL_TRAFFIC=true
ENV DD_DOGSTATSD_NON_LOCAL_TRAFFIC=true
ENV DD_HOSTNAME=datadog-agent-production-3188.up.railway.app
ENV DD_LOGS_ENABLED=true

ARG DD_API_KEY
